# The purpose of this save_to_csvFile.R is to read component .csv files, generated by JSONTOCSV.java, into one file.
# For general using, this code will automatically create an orginal dataset file and an normalized dataset file.

# Please edit the path before run this code.

# The six attributes we will discurss in our project: 
#     elite, yelping_since, votes.count, review count, average stars, fans numbers
rm(list = ls())

# define normalized function
normalized <- function(x, min, max) {
  res <- (x - min)/(max - min)
  return (res)
}

votes <- read.csv("/Users/Serena/Documents/DataMining/final/csv/user_votes.csv")
votes_norm <- normalized(votes, min(votes),max(votes))


friends <- read.csv("/Users/Serena/Documents/DataMining/final/csv/user_friends.csv")
friends_norm <- normalized(friends, min(friends),max(friends))

elite <- read.csv("/Users/Serena/Documents/DataMining/final/csv/user_elite.csv")

yelping_since <- read.csv("/Users/Serena/Documents/DataMining/final/csv/user_yelping_since.csv")

basic <- read.csv("/Users/Serena/Documents/DataMining/final/csv/user_basic_materials.csv")
basic_norm <- cbind(review_count = normalized(basic[,1],min(basic[,1]),max(basic[,1])), 
                    user_id = as.character(basic[,2]), 
                    fans = normalized(basic[,3],min(basic[,3]),max(basic[,3])), 
                    average_stars = normalized(basic[,4],min(basic[,4]),max(basic[,4])))
basic_norm <- as.data.frame(basic_norm)

# generate regular dataset
users <- data.frame(basic[,2],elite,votes,friends,yelping_since,basic[,-2])
names(users)[1] <- "userID"
write.csv(users, file = "/Users/Serena/Documents/DataMining/final/yelp_users_column_narrow.csv",row.names = FALSE)

# generate normalized datasets
users_norm <- data.frame(basic_norm[,2],elite,votes_norm,friends_norm,yelping_since,basic_norm[,-2])
names(users_norm)[1] <- "userID"
write.csv(users_norm, file = "/Users/Serena/Documents/DataMining/final/yelp_users_column_narrow_norm.csv",row.names = FALSE)

